import React, { useState, useEffect } from 'react';

const MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
];

const currentYear = new Date().getFullYear();
const YEARS = Array.from({ length: 5 }, (_, i) => currentYear + i); // Current year + next 4 years

const Marketing = ({
                       activeTab, targetForm, setTargetForm, handleCreateTarget,
                       fetchData, setMarketingTargets, marketingTargets, paginatedMarketingTargets: initialPaginatedTargets, editTargetModal,
                       setEditTargetModal, handleUpdateTarget, filteredMarketingTargets,
                       targetSearchTerm, setTargetSearchTerm, allDevices = [],
                       users = []
                   }) => {

    const [isDeployModalOpen, setIsDeployModalOpen] = useState(false);
    const [isDistDropdownOpen, setIsDistDropdownOpen] = useState(false);
    const [isSrDropdownOpen, setIsSrDropdownOpen] = useState(false);

    // 🚀 NEW: Dropdown States for Timeframe
    const [targetMonth, setTargetMonth] = useState(new Date().getMonth());
    const [targetYear, setTargetYear] = useState(currentYear);

    // Filter Lists for Assignment (Strictly Distributors)
    const distributorList = users.filter(u => u.role === 'DISTRIBUTOR');
    const srList = users.filter(u => u.role === 'SR' && (String(u.parent_id) === String(targetForm.distributor_id || targetForm.distributorId)));

    // 🚀 NEW: Auto-Generate Target Name & Date Range whenever Month, Year, or Distributor changes
    useEffect(() => {
        // Calculate the exact first and last day of the selected month/year
        const start = new Date(targetYear, targetMonth, 1);
        const end = new Date(targetYear, targetMonth + 1, 0);

        // Format to YYYY-MM-DD
        const startStr = `${targetYear}-${String(targetMonth + 1).padStart(2, '0')}-01`;
        const endStr = `${targetYear}-${String(targetMonth + 1).padStart(2, '0')}-${String(end.getDate()).padStart(2, '0')}`;

        // Auto-Generate Name format: DISTRIBUTOR NAME / 26 / APR
        const distName = (targetForm.distributorId || targetForm.distributor_id)
            ? (distributorList.find(d => String(d._id) === String(targetForm.distributorId || targetForm.distributor_id))?.name || 'UNKNOWN').toUpperCase()
            : 'GLOBAL';

        const yearStr = String(targetYear).slice(-2);
        const monthStr = MONTHS[targetMonth].substring(0, 3).toUpperCase();

        const autoGeneratedName = `${distName}/${yearStr}/${monthStr}`;

        // Update the form state invisibly
        setTargetForm(prev => ({
            ...prev,
            name: autoGeneratedName,
            target_name: autoGeneratedName,
            startDate: startStr,
            start_date: startStr,
            endDate: endStr,
            end_date: endStr
        }));

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [targetMonth, targetYear, targetForm.distributorId, targetForm.distributor_id]);

    // 🚀 Strict Unit Calculator mapped to Distributor/SR
    const calculateAchievement = (t) => {
        let idCount = 0;
        let licCount = 0;

        if (allDevices && allDevices.length > 0 && users.length > 0) {
            const sDate = t.start_date ? new Date(t.start_date).setHours(0,0,0,0) : 0;
            const eDate = t.end_date ? new Date(t.end_date).setHours(23,59,59,999) : Infinity;

            allDevices.forEach(d => {
                const dDate = new Date(d.createdAt).getTime();

                if (dDate >= sDate && dDate <= eDate) {
                    const devShopId = d.shopkeeper_id?._id || d.shopkeeper_id;
                    const shop = users.find(u => String(u._id) === String(devShopId));
                    if (!shop) return;

                    let isMatch = false;
                    const targetSr = t.sr_id || t.srId;
                    const targetDist = t.distributor_id || t.distributorId;

                    if (targetSr) {
                        if (String(shop.parent_id) === String(targetSr)) isMatch = true;
                    } else if (targetDist) {
                        if (String(shop.parent_id) === String(targetDist)) {
                            isMatch = true;
                        } else {
                            const sr = users.find(u => String(u._id) === String(shop.parent_id));
                            if (sr && String(sr.parent_id) === String(targetDist)) isMatch = true;
                        }
                    } else {
                        isMatch = true; // Global Plan
                    }

                    if (isMatch) {
                        idCount += 1;
                        licCount += 1;
                    }
                }
            });
        }
        return { idCount, licCount };
    };

    const paginatedCalculatedTargets = initialPaginatedTargets.map(t => {
        const { idCount, licCount } = calculateAchievement(t);
        return { ...t, dynamic_id_achieved: idCount, dynamic_license_achieved: licCount };
    });

    const onFormSubmit = async (e) => {
        e.preventDefault();
        await handleCreateTarget(e);
        setIsDeployModalOpen(false);
    };

    return (
        <div className="space-y-6">
            {/* 🚀 SET TARGET POPUP */}
            {isDeployModalOpen && (
                <div className="fixed inset-0 bg-black/90 flex items-center justify-center p-4 z-[500]">
                    <div className="bg-[#111A35] border border-blue-500/30 rounded-xl p-8 max-w-4xl w-full shadow-2xl relative uppercase font-bold text-[10px]">
                        <button onClick={() => setIsDeployModalOpen(false)} className="absolute top-4 right-4 text-gray-500 hover:text-red-500 text-xl font-black">✕</button>
                        <h3 className="text-xl font-black uppercase text-blue-400 mb-6 border-b border-[#273A60] pb-4 tracking-widest italic">Set Target Plan</h3>

                        <form onSubmit={onFormSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div className="space-y-4">
                                <div className="space-y-1">
                                    <label className="text-gray-500">Target Plan Name (Auto-Generated)</label>
                                    <input
                                        type="text"
                                        value={targetForm.name || ''}
                                        readOnly
                                        className="w-full bg-[#050A15] border border-green-500/30 p-3 text-green-400 outline-none rounded font-black tracking-widest cursor-not-allowed"
                                    />
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="space-y-1">
                                        <label className="text-gray-500">Target Month</label>
                                        <select
                                            value={targetMonth}
                                            onChange={e => setTargetMonth(Number(e.target.value))}
                                            className="w-full bg-[#050A15] border border-[#273A60] p-3 text-blue-300 outline-none rounded uppercase font-bold cursor-pointer"
                                        >
                                            {MONTHS.map((m, idx) => (
                                                <option key={m} value={idx}>{m}</option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-gray-500">Target Year</label>
                                        <select
                                            value={targetYear}
                                            onChange={e => setTargetYear(Number(e.target.value))}
                                            className="w-full bg-[#050A15] border border-[#273A60] p-3 text-blue-300 outline-none rounded uppercase font-bold cursor-pointer"
                                        >
                                            {YEARS.map(y => (
                                                <option key={y} value={y}>{y}</option>
                                            ))}
                                        </select>
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="space-y-1">
                                        <label className="text-gray-500">ID Target (Units)</label>
                                        <input type="number" placeholder="100" value={targetForm.idTarget || ''} onChange={e => setTargetForm({...targetForm, idTarget: e.target.value, id_target: e.target.value, target_amount: e.target.value})} className="w-full bg-[#050A15] border border-[#273A60] p-3 text-white outline-none rounded" required />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-gray-500">License Target (Units)</label>
                                        <input type="number" placeholder="100" value={targetForm.licenseTarget || ''} onChange={e => setTargetForm({...targetForm, licenseTarget: e.target.value, license_target: e.target.value})} className="w-full bg-[#050A15] border border-[#273A60] p-3 text-white outline-none rounded" required />
                                    </div>
                                </div>
                                <div className="space-y-1">
                                    <label className="text-green-500">Success Bonus Amount (৳)</label>
                                    <input type="number" placeholder="0.00" value={targetForm.bonus || ''} onChange={e => setTargetForm({...targetForm, bonus: e.target.value, bonus_amount: e.target.value})} className="w-full bg-[#050A15] border border-green-500/20 p-3 text-green-400 outline-none rounded font-black" />
                                </div>
                            </div>

                            <div className="space-y-4">
                                <div className="space-y-1 relative">
                                    <label className="text-gray-500">Distributor</label>
                                    <div onClick={() => setIsDistDropdownOpen(!isDistDropdownOpen)} className="bg-[#050A15] border border-[#273A60] p-3 text-white rounded cursor-pointer min-h-[45px] flex items-center justify-between uppercase">
                                        {(targetForm.distributorId || targetForm.distributor_id) ? distributorList.find(d => String(d._id) === String(targetForm.distributorId || targetForm.distributor_id))?.name : "CHOOSE DISTRIBUTOR..."}
                                        <span>▼</span>
                                    </div>
                                    {isDistDropdownOpen && (
                                        <div className="absolute top-full left-0 w-full bg-[#0A1128] border border-blue-500/30 max-h-48 overflow-y-auto z-10 shadow-2xl rounded mt-1 uppercase font-bold">
                                            <div onClick={() => { setTargetForm({...targetForm, distributorId: null, distributor_id: null, srId: null, sr_id: null}); setIsDistDropdownOpen(false); }} className="p-2 border-b border-[#273A60] text-red-400 cursor-pointer italic">GLOBAL / CLEAR</div>
                                            {distributorList.map(d => (
                                                <div key={d._id} onClick={() => { setTargetForm({...targetForm, distributorId: d._id, distributor_id: d._id, srId: null, sr_id: null}); setIsDistDropdownOpen(false); }} className="p-2 hover:bg-blue-900 cursor-pointer border-b border-[#050A15]">{d.name}</div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                                <div className="space-y-1 relative">
                                    <label className="text-gray-500">SR (Optional)</label>
                                    <div onClick={() => (targetForm.distributorId || targetForm.distributor_id) && setIsSrDropdownOpen(!isSrDropdownOpen)} className={`bg-[#050A15] border border-[#273A60] p-3 text-white rounded cursor-pointer min-h-[45px] flex items-center justify-between uppercase ${!(targetForm.distributorId || targetForm.distributor_id) && 'opacity-30'}`}>
                                        {(targetForm.srId || targetForm.sr_id) ? srList.find(s => String(s._id) === String(targetForm.srId || targetForm.sr_id))?.name : "ALL SRs"}
                                        <span>▼</span>
                                    </div>
                                    {isSrDropdownOpen && (
                                        <div className="absolute top-full left-0 w-full bg-[#0A1128] border border-blue-500/30 max-h-48 overflow-y-auto z-10 shadow-2xl rounded mt-1 uppercase font-bold">
                                            <div onClick={() => { setTargetForm({...targetForm, srId: null, sr_id: null}); setIsSrDropdownOpen(false); }} className="p-2 border-b border-[#273A60] hover:bg-blue-600 cursor-pointer">ALL SRs</div>
                                            {srList.map(s => (
                                                <div key={s._id} onClick={() => { setTargetForm({...targetForm, srId: s._id, sr_id: s._id}); setIsSrDropdownOpen(false); }} className="p-2 hover:bg-blue-900 cursor-pointer border-b border-[#050A15]">{s.name}</div>
                                            ))}
                                        </div>
                                    )}
                                </div>

                                <div className="bg-blue-900/10 border border-blue-500/20 p-4 rounded text-[9px] text-blue-300 font-mono italic">
                                    Date Range is automatically set from the 1st to the last day of the selected month/year.
                                </div>

                                <button type="submit" className="w-full bg-blue-600 hover:bg-blue-500 text-white font-black py-4 rounded shadow-xl mt-4 transition-all">DEPLOY TARGET PLAN</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* 🚀 TAB 1: ACTIVE PLAN REGISTRY */}
            {activeTab === 'marketing_targets' && (
                <div className="bg-[#111A35] border border-[#273A60] rounded overflow-hidden shadow-2xl">
                    <div className="p-4 bg-[#162447] border-b border-[#273A60] flex flex-col md:flex-row justify-between items-center gap-4">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-blue-300 italic">Active Plan Registry</h3>
                        <div className="flex items-center gap-2">
                            <button onClick={() => setIsDeployModalOpen(true)} className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded text-[10px] font-black shadow-lg shadow-blue-900/30 whitespace-nowrap">SET TARGET</button>
                            <div className="flex items-center bg-[#050A15] border border-[#273A60] px-3 py-2 rounded w-64 shadow-inner">
                                <span className="text-blue-500 mr-2">🔍</span>
                                <input type="text" placeholder="Search..." value={targetSearchTerm} onChange={(e) => setTargetSearchTerm(e.target.value)} className="bg-transparent border-none outline-none text-[10px] text-white w-full uppercase font-black" />
                            </div>
                        </div>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-[9px] font-bold whitespace-nowrap uppercase">
                            <thead className="bg-[#050A15] text-gray-500 tracking-widest font-bold">
                            <tr>
                                <th className="p-4">Target Name</th>
                                <th className="p-4">Assigned To & Timeframe</th>
                                <th className="p-4 text-center">ID Target</th>
                                <th className="p-4 text-center">License Target</th>
                                <th className="p-4 text-right">Bonus (৳)</th>
                                <th className="p-4 text-right">Actions</th>
                            </tr>
                            </thead>
                            <tbody className="divide-y divide-[#162447]">
                            {initialPaginatedTargets.map(t => {
                                const idT = Number(t.id_target || t.idTarget || t.target_amount || 0);
                                const licT = Number(t.license_target || t.licenseTarget || 0);

                                return (
                                    <tr key={t._id || Math.random()} className="hover:bg-blue-900/5 transition-colors font-bold">
                                        <td className="p-4 text-white font-black">{t.target_name || t.name}</td>
                                        <td className="p-4 text-gray-400">
                                            <div className="text-blue-400 text-[8px] mb-1">
                                                {t.sr_id ? `SR: ${users.find(u => String(u._id) === String(t.sr_id))?.name || 'UNKNOWN'}` :
                                                    t.distributor_id ? `DISTRIBUTOR: ${users.find(u => String(u._id) === String(t.distributor_id))?.name || 'UNKNOWN'}` : "GLOBAL PLAN"}
                                            </div>
                                            <div className="text-[7px] font-mono opacity-50">{new Date(t.start_date).toLocaleDateString()} - {new Date(t.end_date).toLocaleDateString()}</div>
                                        </td>
                                        <td className="p-4 text-blue-400 text-center font-mono text-xs">{idT}</td>
                                        <td className="p-4 text-teal-400 text-center font-mono text-xs">{licT}</td>
                                        <td className="p-4 text-green-400 text-right font-mono text-xs">৳{t.bonus_amount || t.bonus || 0}</td>
                                        <td className="p-4 text-right">
                                            <button onClick={() => setEditTargetModal({isOpen: true, target: t})} className="bg-[#162447] border border-blue-900/30 text-blue-300 px-3 py-1.5 rounded text-[8px] hover:bg-blue-600 hover:text-white transition-colors font-black">EDIT</button>
                                        </td>
                                    </tr>
                                );
                            })}
                            {initialPaginatedTargets.length === 0 && <tr><td colSpan="6" className="p-12 text-center text-gray-600 italic tracking-[0.3em]">NO TARGET PLANS DETECTED.</td></tr>}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* 🚀 TAB 2: ACHIEVEMENT MATRIX TABLE */}
            {activeTab === 'marketing_achievements' && (
                <div className="bg-[#111A35] border border-[#273A60] rounded overflow-hidden shadow-2xl">
                    <div className="p-4 bg-[#162447] border-b border-[#273A60] flex justify-between items-center">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-blue-300 italic">Achievement Matrix Tracker</h3>
                        <div className="flex items-center bg-[#050A15] border border-[#273A60] px-3 py-1.5 rounded w-64 shadow-inner">
                            <span className="text-blue-500 mr-2">🔍</span>
                            <input type="text" placeholder="Filter Matrix..." value={targetSearchTerm} onChange={(e) => setTargetSearchTerm(e.target.value)} className="bg-transparent border-none outline-none text-[10px] text-white w-full uppercase font-black" />
                        </div>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-[9px] font-bold whitespace-nowrap uppercase">
                            <thead className="bg-[#050A15] text-gray-500 tracking-widest font-bold">
                            <tr>
                                <th className="p-4">Target Name</th>
                                <th className="p-4 text-center text-blue-400">ID Target</th>
                                <th className="p-4 text-center text-blue-400">ID Achieved</th>
                                <th className="p-4 text-center text-blue-400 border-r border-[#273A60]/30">ID %</th>
                                <th className="p-4 text-center text-teal-400">License Target</th>
                                <th className="p-4 text-center text-teal-400">License Achieved</th>
                                <th className="p-4 text-center text-teal-400 border-r border-[#273A60]/30">License %</th>
                                <th className="p-4 text-center text-green-400">TOTAL %</th>
                            </tr>
                            </thead>
                            <tbody className="divide-y divide-[#162447]">
                            {paginatedCalculatedTargets.map(t => {
                                const idT = Number(t.id_target || t.idTarget || t.target_amount || 0);
                                const idA = Number(t.dynamic_id_achieved || 0);
                                const idPct = idT > 0 ? ((idA / idT) * 100).toFixed(1) : 0;

                                const licT = Number(t.license_target || t.licenseTarget || 0);
                                const licA = Number(t.dynamic_license_achieved || 0);
                                const licPct = licT > 0 ? ((licA / licT) * 100).toFixed(1) : 0;

                                const totalPct = ((Number(idPct) + Number(licPct)) / 2).toFixed(1);

                                return (
                                    <tr key={t._id || Math.random()} className="hover:bg-blue-900/5 transition-colors font-bold">
                                        <td className="p-4 text-white">
                                            {t.target_name || t.name}
                                            <div className="text-[7px] text-gray-500 mt-1 font-mono">{new Date(t.start_date).toLocaleDateString('en-GB')} - {new Date(t.end_date).toLocaleDateString('en-GB')}</div>
                                        </td>
                                        <td className="p-4 text-blue-400 text-center font-mono">{idT}</td>
                                        <td className="p-4 text-blue-200 text-center font-mono">{idA}</td>
                                        <td className={`p-4 text-center font-black border-r border-[#273A60]/30 text-[10px] ${idPct >= 100 ? 'text-green-500' : 'text-blue-500'}`}>{idPct}%</td>

                                        <td className="p-4 text-teal-500 text-center font-mono">{licT}</td>
                                        <td className="p-4 text-teal-200 text-center font-mono">{licA}</td>
                                        <td className={`p-4 text-center font-black border-r border-[#273A60]/30 text-[10px] ${licPct >= 100 ? 'text-green-500' : 'text-teal-500'}`}>{licPct}%</td>

                                        <td className="p-4 text-center">
                                            <span className={`px-3 py-1 rounded-full text-[10px] font-black shadow-lg ${totalPct >= 100 ? 'bg-green-600 text-white animate-pulse' : 'bg-yellow-600/20 text-yellow-500 border border-yellow-500/30'}`}>{totalPct}%</span>
                                        </td>
                                    </tr>
                                );
                            })}
                            {paginatedCalculatedTargets.length === 0 && <tr><td colSpan="8" className="p-12 text-center text-gray-600 italic tracking-[0.3em]">NO ACHIEVEMENT DATA FOUND.</td></tr>}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* 🚀 EDIT MODAL */}
            {editTargetModal.isOpen && editTargetModal.target && (
                <div className="fixed inset-0 bg-black/90 flex items-center justify-center p-4 z-[600]">
                    <div className="bg-[#111A35] border border-[#273A60] rounded-xl p-8 max-w-2xl w-full shadow-2xl relative uppercase font-bold text-[10px]">
                        <button onClick={() => setEditTargetModal({ isOpen: false, target: null })} className="absolute top-4 right-4 text-gray-500 hover:text-red-500 text-xl font-black">✕</button>
                        <h3 className="text-xl font-black uppercase text-blue-400 mb-6 border-b border-[#273A60] pb-4 tracking-widest italic">Modify Plan Nodes</h3>
                        <form onSubmit={handleUpdateTarget} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div className="flex flex-col md:col-span-2">
                                <label className="text-gray-500 mb-1">Target Name</label>
                                <input type="text" value={editTargetModal.target.target_name || editTargetModal.target.name || ''} onChange={e => setEditTargetModal({ ...editTargetModal, target: { ...editTargetModal.target, target_name: e.target.value } })} className="bg-[#0A1128] border border-[#273A60] p-3 text-white outline-none rounded" required />
                            </div>
                            <div className="flex flex-col">
                                <label className="text-blue-400 mb-1">ID Target (Units)</label>
                                <input type="number" value={editTargetModal.target.id_target ?? editTargetModal.target.idTarget ?? editTargetModal.target.target_amount ?? ''} onChange={e => setEditTargetModal({ ...editTargetModal, target: { ...editTargetModal.target, id_target: Number(e.target.value), target_amount: Number(e.target.value) } })} className="bg-[#0A1128] border border-blue-500/20 p-3 text-white outline-none rounded" />
                            </div>
                            <div className="flex flex-col">
                                <label className="text-teal-400 mb-1">License Target (Units)</label>
                                <input type="number" value={editTargetModal.target.license_target ?? editTargetModal.target.licenseTarget ?? ''} onChange={e => setEditTargetModal({ ...editTargetModal, target: { ...editTargetModal.target, license_target: Number(e.target.value) } })} className="bg-[#0A1128] border border-teal-500/20 p-3 text-white outline-none rounded" />
                            </div>
                            <button type="submit" className="bg-blue-600 hover:bg-blue-500 text-white font-black py-4 rounded shadow-lg md:col-span-2 mt-4 transition-all">UPDATE PLAN NODES</button>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Marketing;